### ISSUE TITLE
History setup bug

### ISSUE THREAD

**Issue by BugLight** [willothy/nvim-cokeline#153]
Hi!
I was configuring my mappings to jump between buffers in a historic order. And then I noticed that the object returned by `require('cokeline.history')` (https://github.com/willothy/nvim-cokeline/blob/main/README.md?plain=1#L877 see this example in docs) is not set up (its fields are not initialized).
However `_G.cokeline.history` works fine :)

This is how the error looks like:
<img width="1378" alt="Screenshot 2023-08-13 at 15 58 29" src="https://github.com/willothy/nvim-cokeline/assets/13618366/e3f29324-b891-4847-a54d-1acb610f815a">

I think it is pretty easy to fix. If I have some spare time I will do it myself and will send a PR.
Also thank you for the awesome plugin!

**Comment by willothy** [comment]
This is very interesting. I actually figured out that the issue came from the uses of "/" in `require` calls. Apparently there is some different between `.` and `/`, though I'm not quite sure what. Until now I had kept with `/` because that's what the creator of the plugin did initially, but I've just changed all require calls to use `.` which should fix it.
