### ISSUE TITLE
Mapping `<Plug>(cokeline-focus-*)` doesn't work for unlisted buffers

### ISSUE THREAD

**Issue by EtiamNullam** [willothy/nvim-cokeline#61]
Mappings `<Plug>(cokeline-focus-next)` and `<Plug>(cokeline-focus-prev)` won't switch buffer when executed from an unlisted buffer.

If buffer is listed by `set buflisted` or `lua vim.o.buflisted = true` then it will work again (for this buffer).

**Comment by willothy** [comment]
This is actually expected behavior, but sure why it's marked as a bug. Unlisted buffers aren't shown in the bufferline, and the next/prev mappings only switch within the bufferline. 

Would it be helpful if I defer to the filter functions for showing / hiding listed buffers so that you can have unlisted buffers shown in the bufferline?

**Comment by willothy** [comment]
Added fallback to history for the focus by step commands, so in unlisted buffers the previously accessed buffer will be focused.
